
import type { AppProps } from 'next/app';
import Head from 'next/head';
import 'tailwindcss/tailwind.css';
import { Footer } from '../components/footer';
import { NavBar } from '../components/NavBar'

function MyApp({ Component, pageProps }: AppProps) {
  return(
   <>
      <Head>
        <title>Coffee Pack</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content='width=device-width, initial-scale=1'/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/logo.png"/>
      </Head>
      {/* <NavBar/> */}

    <Component {...pageProps} />;
    <Footer/>
   </> 
    ) 
}
export default MyApp;