
import type { AppProps } from 'next/app';
import Head from 'next/head';
import 'tailwindcss/tailwind.css';
import { Navbar } from '../components/navbar';

function MyApp({ Component, pageProps }: AppProps) {
  return(
   <>
      <Head>
        <title>Coffee Pack</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/logo.png"/>
      </Head>
      <Navbar/>

    <Component {...pageProps} />;
   </> 
    ) 
}
export default MyApp;